package canon

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func Render(root string, options RenderOptions) (RenderResult, error) {
	if err := EnsureLayout(root, options.Write); err != nil {
		return RenderResult{}, err
	}

	specs, err := loadSpecs(root)
	if err != nil {
		return RenderResult{}, err
	}
	index := buildIndex(specs)

	domainDocs, domainContributors, domainChecksums := buildDomainDocuments(index)
	interactionDocs, interactionContributors := buildInteractionDocuments(index)

	manifest := buildManifest(len(specs), domainContributors, domainChecksums, sortedKeys(interactionContributors))
	indexYAML := serializeIndexYAML(index)
	gaps := defaultGaps()

	outputs := map[string]string{
		filepath.Join(root, ".canon", "index.yaml"):   indexYAML,
		filepath.Join(root, "state", "manifest.yaml"): manifest,
		filepath.Join(root, "state", "gaps.md"):       gaps,
	}
	for domain, text := range domainDocs {
		outputs[filepath.Join(root, "state", domain+".md")] = text
	}
	for name, text := range interactionDocs {
		outputs[filepath.Join(root, "state", "interactions", name+".md")] = text
	}

	if err := validateOutputPaths(root, outputs); err != nil {
		return RenderResult{}, err
	}

	written := 0
	removedCount := 0
	updatedCount := 0
	if options.Write {
		removed, err := cleanupStaleGeneratedFiles(root, outputs)
		if err != nil {
			return RenderResult{}, err
		}
		removedCount = removed
		written += removed

		paths := make([]string, 0, len(outputs))
		for path := range outputs {
			paths = append(paths, path)
		}
		sort.Strings(paths)
		for _, path := range paths {
			changed, err := writeTextIfChanged(path, outputs[path])
			if err != nil {
				return RenderResult{}, err
			}
			if changed {
				updatedCount++
				written++
			}
		}
	}

	return RenderResult{
		FilesRemoved:    removedCount,
		FilesUpdated:    updatedCount,
		FilesWritten:    written,
		DomainChecksums: domainChecksums,
	}, nil
}

func buildDomainDocuments(index Index) (map[string]string, map[string][]string, map[string]string) {
	domainDocs := make(map[string]string)
	contributors := make(map[string][]string)
	checksums := make(map[string]string)

	domains := sortedKeys(index.Domains)
	for _, domain := range domains {
		specIDs := index.Domains[domain]
		specs := make([]Spec, 0, len(specIDs))
		for _, id := range specIDs {
			specs = append(specs, index.Specs[id])
		}
		sortSpecsStable(specs)

		ids := make([]string, 0, len(specs))
		for _, spec := range specs {
			ids = append(ids, spec.ID)
		}
		contributors[domain] = ids

		lines := []string{
			"<!-- AUTO-GENERATED by canon. Do not edit directly. -->",
			"<!-- Domain: " + domain + " -->",
			"<!-- Contributing specs: " + strings.Join(ids, ", ") + " -->",
			"",
			"# " + strings.ToUpper(domain),
			"",
		}
		for _, spec := range specs {
			lines = append(lines,
				"## "+spec.ID+": "+spec.Title+" ["+spec.Type+"]",
				"",
				spec.Body,
				"",
			)
		}
		content := strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"
		domainDocs[domain] = content
		checksums[domain] = checksum(content)
	}

	return domainDocs, contributors, checksums
}

func buildInteractionDocuments(index Index) (map[string]string, map[string][]string) {
	keyToSpecs := make(map[string][]Spec)
	for _, spec := range index.Specs {
		touched := mustInclude(spec.TouchedDomains, spec.Domain)
		if len(touched) < 2 {
			continue
		}
		for i := 0; i < len(touched); i++ {
			for j := i + 1; j < len(touched); j++ {
				left := touched[i]
				right := touched[j]
				if left > right {
					left, right = right, left
				}
				key := left + "-" + right
				keyToSpecs[key] = append(keyToSpecs[key], spec)
			}
		}
	}

	docs := make(map[string]string)
	contributors := make(map[string][]string)
	keys := sortedKeys(keyToSpecs)
	for _, key := range keys {
		specs := keyToSpecs[key]
		sortSpecsStable(specs)
		ids := make([]string, 0, len(specs))
		parts := strings.SplitN(key, "-", 2)
		left, right := parts[0], parts[1]

		lines := []string{
			"<!-- AUTO-GENERATED by canon. Do not edit directly. -->",
			"<!-- Domains: " + left + ", " + right + " -->",
			"<!-- Contributing specs: " + joinSpecIDs(specs) + " -->",
			"",
			"# Interaction " + left + " and " + right,
			"",
		}
		for _, spec := range specs {
			ids = append(ids, spec.ID)
			lines = append(lines,
				"## "+spec.ID+": "+spec.Title,
				"Source: "+filepath.ToSlash(spec.Path),
				"",
			)
		}
		contributors[key] = ids
		docs[key] = strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"
	}

	return docs, contributors
}

func buildManifest(totalSpecs int, domainContributors map[string][]string, domainChecksums map[string]string, interactionFiles []string) string {
	domainNames := sortedKeys(domainChecksums)
	builder := strings.Builder{}
	for _, domain := range domainNames {
		builder.WriteString(domain)
		builder.WriteString(":")
		builder.WriteString(domainChecksums[domain])
	}
	stateVersion := "000000000000"
	if builder.Len() > 0 {
		stateVersion = checksum(builder.String())[:12]
	}

	lines := []string{
		"state_version: " + stateVersion,
		fmt.Sprintf("total_specs: %d", totalSpecs),
		"domain_versions:",
	}

	if len(domainNames) == 0 {
		lines = append(lines, "  {}")
	} else {
		for _, domain := range domainNames {
			lines = append(lines,
				"  "+domain+":",
				"    contributing_specs: "+renderList(domainContributors[domain]),
				"    checksum: sha256:"+domainChecksums[domain],
			)
		}
	}

	lines = append(lines, "interaction_files:")
	if len(interactionFiles) == 0 {
		lines = append(lines, "  []")
	} else {
		for _, name := range interactionFiles {
			lines = append(lines, "  - state/interactions/"+name+".md")
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

func defaultGaps() string {
	return "<!-- AUTO-GENERATED by canon. Do not edit directly. -->\n" +
		"# Known Gaps\n\n" +
		"No unresolved gaps were materialized by the deterministic renderer.\n"
}

func validateOutputPaths(root string, outputs map[string]string) error {
	for path := range outputs {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if rel == ".canon/index.yaml" || rel == "state/manifest.yaml" || rel == "state/gaps.md" {
			continue
		}
		if strings.HasPrefix(rel, "state/interactions/") && strings.HasSuffix(rel, ".md") {
			continue
		}
		if strings.HasPrefix(rel, "state/") && strings.HasSuffix(rel, ".md") && !strings.Contains(strings.TrimPrefix(rel, "state/"), "/") {
			continue
		}
		return fmt.Errorf("output path blocked by policy: %s", rel)
	}
	return nil
}

func cleanupStaleGeneratedFiles(root string, desired map[string]string) (int, error) {
	desiredRel := make(map[string]struct{}, len(desired))
	for path := range desired {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return 0, err
		}
		desiredRel[filepath.ToSlash(rel)] = struct{}{}
	}

	removed := 0
	stateGlob := filepath.Join(root, "state", "*.md")
	stateFiles, err := filepath.Glob(stateGlob)
	if err != nil {
		return 0, err
	}
	for _, path := range stateFiles {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return 0, err
		}
		rel = filepath.ToSlash(rel)
		if _, ok := desiredRel[rel]; ok {
			continue
		}
		if err := os.Remove(path); err != nil {
			return 0, err
		}
		removed++
	}

	interactionGlob := filepath.Join(root, "state", "interactions", "*.md")
	interactionFiles, err := filepath.Glob(interactionGlob)
	if err != nil {
		return 0, err
	}
	for _, path := range interactionFiles {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return 0, err
		}
		rel = filepath.ToSlash(rel)
		if _, ok := desiredRel[rel]; ok {
			continue
		}
		if err := os.Remove(path); err != nil {
			return 0, err
		}
		removed++
	}

	return removed, nil
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func joinSpecIDs(specs []Spec) string {
	ids := make([]string, 0, len(specs))
	for _, spec := range specs {
		ids = append(ids, spec.ID)
	}
	return strings.Join(ids, ", ")
}
