package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"canon/internal/canon"
)

func TestVersionCommandPrintsCurrentVersion(t *testing.T) {
	out := captureStdout(t, func() {
		if err := run([]string{"version"}); err != nil {
			t.Fatalf("version command failed: %v", err)
		}
	})

	if strings.TrimSpace(out) != "canon v0.1.0" {
		t.Fatalf("expected version output, got %q", out)
	}
}

func TestVersionFlagAliasPrintsCurrentVersion(t *testing.T) {
	out := captureStdout(t, func() {
		if err := run([]string{"--version"}); err != nil {
			t.Fatalf("--version command failed: %v", err)
		}
	})

	if strings.TrimSpace(out) != "canon v0.1.0" {
		t.Fatalf("expected version output, got %q", out)
	}
}

func TestVersionCommandShortPrintsVersionOnly(t *testing.T) {
	out := captureStdout(t, func() {
		if err := run([]string{"version", "--short"}); err != nil {
			t.Fatalf("version --short command failed: %v", err)
		}
	})

	if strings.TrimSpace(out) != "v0.1.0" {
		t.Fatalf("expected short version output, got %q", out)
	}
}

func TestVersionCommandRejectsPositionalArgs(t *testing.T) {
	err := run([]string{"version", "extra"})
	if err == nil {
		t.Fatalf("expected error for version positional args")
	}
	if !strings.Contains(err.Error(), "version does not accept positional arguments") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestRenderDefaultsToAIRenderAndWritesStateFolder(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:   "Billing retries must happen daily.",
		Title:  "Billing Retry",
		Domain: "billing",
	}); err != nil {
		t.Fatalf("Ingest failed: %v", err)
	}

	binDir := t.TempDir()
	codexPath := filepath.Join(binDir, "codex")
	script := `#!/bin/sh
out=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    out="$2"
    shift 2
    continue
  fi
  shift
done

if [ -z "$out" ]; then
  echo "missing output path" >&2
  exit 2
fi

cat >/dev/null

cat <<'JSON' > "$out"
{
  "model": "codex-headless",
  "domain_docs": [
    {
      "domain": "billing",
      "body": "<!-- AUTO-GENERATED by canon. Do not edit directly. -->\n<!-- Domain: billing -->\n<!-- Contributing specs: spec-000 -->\n\n# BILLING\n\n## Effective State\n\n- AI-effective state for billing.\n"
    }
  ],
  "interaction_docs": [],
  "gaps": "<!-- AUTO-GENERATED by canon. Do not edit directly. -->\n# Known Gaps\n\nNo unresolved gaps.\n"
}
JSON
`
	if err := os.WriteFile(codexPath, []byte(script), 0o755); err != nil {
		t.Fatalf("failed writing fake codex binary: %v", err)
	}

	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("HOME", t.TempDir())

	if err := run([]string{"render", "--root", root, "--write"}); err != nil {
		t.Fatalf("render command failed: %v", err)
	}

	billingState, err := os.ReadFile(filepath.Join(root, "state", "billing.md"))
	if err != nil {
		t.Fatalf("failed reading billing state file: %v", err)
	}
	if !strings.Contains(string(billingState), "AI-effective state for billing.") {
		t.Fatalf("expected AI render content in state/billing.md")
	}

	if _, err := os.Stat(filepath.Join(root, "state2")); err == nil {
		t.Fatalf("did not expect render output in state2/")
	} else if !os.IsNotExist(err) {
		t.Fatalf("failed checking state2 folder: %v", err)
	}
}

func TestInitCommandAIOffCreatesLayoutOnly(t *testing.T) {
	root := t.TempDir()

	out := captureStdout(t, func() {
		if err := run([]string{"init", "--root", root, "--ai", "off"}); err != nil {
			t.Fatalf("init command failed: %v", err)
		}
	})

	if !strings.Contains(out, "layout ready at") {
		t.Fatalf("expected layout message, got:\n%s", out)
	}
	if st, err := os.Stat(filepath.Join(root, ".canon", "specs")); err != nil || !st.IsDir() {
		t.Fatalf("expected .canon/specs directory to exist, err=%v", err)
	}
	specs, err := canon.LoadSpecsForCLI(root)
	if err != nil {
		t.Fatalf("LoadSpecsForCLI failed: %v", err)
	}
	if len(specs) != 0 {
		t.Fatalf("expected no specs for --ai off, got %d", len(specs))
	}
}

func TestInitCommandResponseFileAcceptAllIngestsSpecs(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte("# Sample\n"), 0o644); err != nil {
		t.Fatalf("write README failed: %v", err)
	}

	responsePath := filepath.Join(root, "init-response.json")
	response := map[string]any{
		"model":           "test-model",
		"project_summary": "Sample project.",
		"specs": []map[string]any{
			{
				"id":              "a1a1a1a",
				"type":            "feature",
				"title":           "Auth",
				"domain":          "auth",
				"depends_on":      []string{},
				"touched_domains": []string{"auth"},
				"body":            "Users can sign in.",
				"review_hint":     "Auth hint.",
			},
			{
				"id":              "b2b2b2b",
				"type":            "technical",
				"title":           "API",
				"domain":          "api",
				"depends_on":      []string{"a1a1a1a"},
				"touched_domains": []string{"api", "auth"},
				"body":            "API validates auth tokens.",
				"review_hint":     "API hint.",
			},
		},
	}
	writeGCResponse(t, responsePath, response)

	out := captureStdout(t, func() {
		if err := run([]string{"init", "--root", root, "--response-file", responsePath, "--accept-all"}); err != nil {
			t.Fatalf("init command failed: %v", err)
		}
	})

	if !strings.Contains(out, "Generating specs... done (2 specs produced)") {
		t.Fatalf("expected generation output, got:\n%s", out)
	}
	if !strings.Contains(out, "layout ready at") {
		t.Fatalf("expected final layout message, got:\n%s", out)
	}

	specs, err := canon.LoadSpecsForCLI(root)
	if err != nil {
		t.Fatalf("LoadSpecsForCLI failed: %v", err)
	}
	if len(specs) != 2 {
		t.Fatalf("expected 2 ingested specs, got %d", len(specs))
	}
	entries, err := canon.LoadLedger(root)
	if err != nil {
		t.Fatalf("LoadLedger failed: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("expected 2 ledger entries, got %d", len(entries))
	}
}

func TestGcCommandDryRunNoWrite(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "api-a1",
		Text:    "Clients must include an API key with every request.",
		Title:   "API Key Presence",
		Domain:  "api",
		Created: "2026-02-21T08:00:00Z",
	}); err != nil {
		t.Fatalf("ingest api-a1 failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "api-b2",
		Text:    "Expired API keys should be rejected.",
		Title:   "API Key Expiry",
		Domain:  "api",
		Created: "2026-02-21T09:00:00Z",
	}); err != nil {
		t.Fatalf("ingest api-b2 failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "platform-a",
		Text:    "User identity tokens are validated at login.",
		Title:   "Identity Validation",
		Domain:  "platform",
		Created: "2026-02-21T10:00:00Z",
	}); err != nil {
		t.Fatalf("ingest platform-a failed: %v", err)
	}

	entriesBefore, err := canon.LoadLedger(root)
	if err != nil {
		t.Fatalf("LoadLedger before failed: %v", err)
	}

	responsePath := filepath.Join(root, "gc-response.json")
	response := map[string]any{
		"model":   "test-model",
		"summary": "Consolidate api requirements.",
		"consolidated_specs": []any{
			map[string]any{
				"id":              "api-consolidated",
				"type":            "feature",
				"title":           "API Auth and Expiry Controls",
				"domain":          "api",
				"created":         "2026-02-21T10:30:00Z",
				"depends_on":      []string{"platform-a"},
				"touched_domains": []string{"api"},
				"consolidates":    []string{"api-a1", "api-b2"},
				"body":            "Clients must include API keys and expired keys must be rejected.",
			},
		},
	}
	writeGCResponse(t, responsePath, response)

	out := captureStdout(t, func() {
		if err := run([]string{
			"gc",
			"--root", root,
			"--domain", "api",
			"--response-file", responsePath,
			"--min-specs", "1",
		}); err != nil {
			t.Fatalf("gc command failed: %v", err)
		}
	})

	if !strings.Contains(out, "gc plan for domain: api") {
		t.Fatalf("expected gc plan output, got:\n%s", out)
	}
	if !strings.Contains(out, "dry run complete; use --write to execute") {
		t.Fatalf("expected dry-run completion message, got:\n%s", out)
	}

	entriesAfter, err := canon.LoadLedger(root)
	if err != nil {
		t.Fatalf("LoadLedger after failed: %v", err)
	}
	if len(entriesAfter) != len(entriesBefore) {
		t.Fatalf("expected no new ledger entries during dry run")
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "specs", "api-consolidated.spec.md")); err == nil {
		t.Fatalf("did not expect consolidated file to be written in dry run")
	} else if !os.IsNotExist(err) {
		t.Fatalf("unexpected error checking consolidated file: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "archive", "specs", "api-a1.spec.md")); err == nil {
		t.Fatalf("expected api-a1 to remain active during dry run")
	} else if !os.IsNotExist(err) {
		t.Fatalf("unexpected error checking archived api-a1 spec path: %v", err)
	}
}

func TestGcCommandWriteConsolidatesSpecsAndArchivesSources(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "api-a1",
		Text:    "Clients must include an API key with every request.",
		Title:   "API Key Presence",
		Domain:  "api",
		Created: "2026-02-21T08:00:00Z",
	}); err != nil {
		t.Fatalf("ingest api-a1 failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "api-b2",
		Text:    "Expired API keys should be rejected.",
		Title:   "API Key Expiry",
		Domain:  "api",
		Created: "2026-02-21T09:00:00Z",
	}); err != nil {
		t.Fatalf("ingest api-b2 failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ID:      "platform-a",
		Text:    "User identity tokens are validated at login.",
		Title:   "Identity Validation",
		Domain:  "platform",
		Created: "2026-02-21T10:00:00Z",
	}); err != nil {
		t.Fatalf("ingest platform-a failed: %v", err)
	}

	responsePath := filepath.Join(root, "gc-response.json")
	response := map[string]any{
		"model":   "test-model",
		"summary": "Consolidate api requirements.",
		"consolidated_specs": []any{
			map[string]any{
				"id":              "api-consolidated",
				"type":            "feature",
				"title":           "API Auth and Expiry Controls",
				"domain":          "api",
				"created":         "2026-02-21T10:30:00Z",
				"depends_on":      []string{"platform-a"},
				"touched_domains": []string{"api"},
				"consolidates":    []string{"api-a1", "api-b2"},
				"body":            "Clients must include API keys and expired keys must be rejected.",
			},
		},
	}
	writeGCResponse(t, responsePath, response)

	out := captureStdout(t, func() {
		if err := run([]string{
			"gc",
			"--root", root,
			"--domain", "api",
			"--write",
			"--response-file", responsePath,
			"--min-specs", "1",
		}); err != nil {
			t.Fatalf("gc command failed: %v", err)
		}
	})

	if !strings.Contains(out, "gc complete for domain: api") {
		t.Fatalf("expected completion output, got:\n%s", out)
	}
	if !strings.Contains(out, "run 'canon render --write' to update state") {
		t.Fatalf("expected render instruction output, got:\n%s", out)
	}

	if _, err := os.Stat(filepath.Join(root, ".canon", "specs", "api-a1.spec.md")); !os.IsNotExist(err) {
		t.Fatalf("expected api-a1 spec to be archived, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "archive", "specs", "api-a1.spec.md")); err != nil {
		t.Fatalf("expected archived api-a1 spec")
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "archive", "sources", "api-a1.source.md")); err != nil {
		t.Fatalf("expected archived api-a1 source")
	}

	if _, err := os.Stat(filepath.Join(root, ".canon", "specs", "api-b2.spec.md")); !os.IsNotExist(err) {
		t.Fatalf("expected api-b2 spec to be archived, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "archive", "specs", "api-b2.spec.md")); err != nil {
		t.Fatalf("expected archived api-b2 spec")
	}
	if _, err := os.Stat(filepath.Join(root, ".canon", "archive", "sources", "api-b2.source.md")); err != nil {
		t.Fatalf("expected archived api-b2 source")
	}

	if _, err := os.Stat(filepath.Join(root, ".canon", "specs", "api-consolidated.spec.md")); err != nil {
		t.Fatalf("expected consolidated spec output file")
	}

	consolidatedText, err := os.ReadFile(filepath.Join(root, ".canon", "specs", "api-consolidated.spec.md"))
	if err != nil {
		t.Fatalf("failed to read consolidated spec: %v", err)
	}
	conText := string(consolidatedText)
	if !strings.Contains(conText, "consolidates: [api-a1, api-b2]") {
		t.Fatalf("expected consolidated frontmatter to include source ids, got:\n%s", conText)
	}

	entries, err := canon.LoadLedger(root)
	if err != nil {
		t.Fatalf("LoadLedger after failed: %v", err)
	}
	var found bool
	var op string
	for _, entry := range entries {
		if entry.SpecID == "api-consolidated" {
			found = true
			op = entry.Operation
			break
		}
	}
	if !found {
		t.Fatalf("expected ledger entry for api-consolidated")
	}
	if op != "consolidation" {
		t.Fatalf("expected ledger operation consolidation, got %q", op)
	}
}

func TestLogGraphFlagsRenderDependencyGraph(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:   "Base auth requirement.",
		ID:     "spec-a",
		Title:  "Auth Base",
		Type:   "feature",
		Domain: "auth",
	}); err != nil {
		t.Fatalf("Ingest spec-a failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:      "API depends on auth.",
		ID:        "spec-b",
		Title:     "Rate Limits",
		Type:      "feature",
		Domain:    "api",
		DependsOn: []string{"spec-a"},
	}); err != nil {
		t.Fatalf("Ingest spec-b failed: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{"log", "--root", root, "--graph", "--oneline", "--all"}); err != nil {
			t.Fatalf("log command failed: %v", err)
		}
	})

	if !strings.Contains(out, "* spec-b") {
		t.Fatalf("expected spec-b graph node, got:\n%s", out)
	}
	if !strings.Contains(out, "* spec-a") {
		t.Fatalf("expected spec-a graph node, got:\n%s", out)
	}
	if strings.Contains(out, "|->") {
		t.Fatalf("did not expect separate dependency edge lines, got:\n%s", out)
	}
}

func TestLogShowTagsFlag(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:      "Base auth requirement.",
		ID:        "spec-a",
		Title:     "Auth Base",
		Type:      "feature",
		Domain:    "auth",
		Created:   "2026-02-19T10:00:00Z",
		Parents:   nil,
		DependsOn: nil,
	}); err != nil {
		t.Fatalf("Ingest spec-a failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:      "API depends on auth.",
		ID:        "spec-b",
		Title:     "Rate Limits",
		Type:      "feature",
		Domain:    "api",
		DependsOn: []string{"spec-a"},
	}); err != nil {
		t.Fatalf("Ingest spec-b failed: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{"log", "--root", root, "--graph", "--oneline", "--all"}); err != nil {
			t.Fatalf("log command failed: %v", err)
		}
	})
	if strings.Contains(out, "[feature/auth]") || strings.Contains(out, "[feature/api]") {
		t.Fatalf("expected qualified tags hidden by default, got:\n%s", out)
	}

	out = captureStdout(t, func() {
		if err := run([]string{"log", "--root", root, "--graph", "--oneline", "--all", "--show-tags"}); err != nil {
			t.Fatalf("log command with --show-tags failed: %v", err)
		}
	})
	if !strings.Contains(out, "[feature/auth]") {
		t.Fatalf("expected qualified tag for spec-a with --show-tags, got:\n%s", out)
	}
	if !strings.Contains(out, "[feature/api]") {
		t.Fatalf("expected qualified tag for spec-b with --show-tags, got:\n%s", out)
	}
}

func TestLogDefaultsUseRelativeDatesAndAllHeads(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:      "Auth requirements with no dependencies.",
		ID:        "auth-a1",
		Title:     "Auth Baseline",
		Type:      "feature",
		Domain:    "auth",
		Created:   "2026-02-19T10:00:00Z",
		Parents:   nil,
		DependsOn: nil,
	}); err != nil {
		t.Fatalf("Ingest auth-a1 failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:    "Billing requirements with no dependencies.",
		ID:      "billing-a1",
		Title:   "Billing Baseline",
		Type:    "feature",
		Domain:  "billing",
		Created: "2026-02-18T10:00:00Z",
	}); err != nil {
		t.Fatalf("Ingest billing-a1 failed: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{"log", "--root", root}); err != nil {
			t.Fatalf("log command failed: %v", err)
		}
	})

	if !strings.Contains(out, "Spec: auth-a1") || !strings.Contains(out, "Spec: billing-a1") {
		t.Fatalf("expected both disconnected heads with default --all behavior, got:\n%s", out)
	}

	relativeDate := regexp.MustCompile(`\b(ago|just now|in moments|from now)\b`)
	if !relativeDate.MatchString(out) {
		t.Fatalf("expected relative date output by default, got:\n%s", out)
	}
}

func captureStdout(t *testing.T, fn func()) string {
	t.Helper()

	originalStdout := os.Stdout
	reader, writer, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe failed: %v", err)
	}

	os.Stdout = writer
	defer func() {
		os.Stdout = originalStdout
	}()

	fn()

	if err := writer.Close(); err != nil {
		t.Fatalf("closing writer failed: %v", err)
	}
	out, err := io.ReadAll(reader)
	if err != nil {
		t.Fatalf("reading captured output failed: %v", err)
	}
	if err := reader.Close(); err != nil {
		t.Fatalf("closing reader failed: %v", err)
	}
	return string(out)
}

func TestResetCommandResetsToReferenceSpec(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text: `---
id: spec-501
type: feature
title: "Initial Policy"
domain: api
created: 2026-02-19T12:00:00Z
depends_on: []
touched_domains: [api]
---
Initial API policy.`,
	}); err != nil {
		t.Fatalf("first ingest failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		Text: `---
id: spec-502
type: feature
title: "Follow Up"
domain: api
created: 2026-02-19T12:10:00Z
depends_on: [spec-501]
touched_domains: [api]
---
Follow-up API policy.`,
	}); err != nil {
		t.Fatalf("second ingest failed: %v", err)
	}

	if err := run([]string{"reset", "--root", root, "spec-501"}); err != nil {
		t.Fatalf("reset command failed: %v", err)
	}

	if _, err := os.Stat(filepath.Join(root, ".canon", "specs", "spec-502.spec.md")); !os.IsNotExist(err) {
		t.Fatalf("expected spec-502 to be removed, err=%v", err)
	}
	entries, err := canon.LoadLedger(root)
	if err != nil {
		t.Fatalf("LoadLedger failed: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("expected 1 ledger entry after reset, got %d", len(entries))
	}
	if entries[0].SpecID != "spec-501" {
		t.Fatalf("expected remaining ledger entry spec-501, got %s", entries[0].SpecID)
	}
}

func TestBlameCommandDirectMatchWithResponseFile(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	ingestSpecForBlame(t, root, "a1b2c3d", "API Endpoint Design and Versioning", "api", "2026-01-15T10:30:00Z", []string{"api"},
		"All list endpoints must return paginated responses.\nDefault page size must be 25 items.\nClients may override page size up to a maximum of 100.",
	)

	responsePath := filepath.Join(root, "blame-response.json")
	response := `{
  "model": "codex-headless",
  "found": true,
  "results": [
    {
      "spec_id": "a1b2c3d",
      "confidence": "high",
      "relevant_lines": [
        "All list endpoints must return paginated responses.",
        "Default page size must be 25 items.",
        "Clients may override page size up to a maximum of 100."
      ]
    }
  ]
}`
	if err := os.WriteFile(responsePath, []byte(response), 0o644); err != nil {
		t.Fatalf("failed writing response file: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{
			"blame",
			"--root", root,
			"--response-file", responsePath,
			"API responses are paginated with a default page size of 25",
		}); err != nil {
			t.Fatalf("blame command failed: %v", err)
		}
	})

	if !strings.Contains(out, "blame: 1 spec found") {
		t.Fatalf("expected single result summary, got:\n%s", out)
	}
	if !strings.Contains(out, "spec: a1b2c3d") {
		t.Fatalf("expected matching spec id in output, got:\n%s", out)
	}
	if !strings.Contains(out, "confidence: high") {
		t.Fatalf("expected confidence in output, got:\n%s", out)
	}
	if !strings.Contains(out, "> Default page size must be 25 items.") {
		t.Fatalf("expected relevant lines in output, got:\n%s", out)
	}
}

func TestBlameCommandMultipleResults(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	ingestSpecForBlame(t, root, "f4e5d6c", "User Registration Flow", "auth", "2026-01-10T09:00:00Z", []string{"auth"},
		"New users must verify their email address before account activation.\nUnverified accounts must be restricted to read-only access.",
	)
	ingestSpecForBlame(t, root, "7890abc", "Billing and Subscription Gating", "billing", "2026-02-01T14:00:00Z", []string{"billing", "auth"},
		"Paid features must only be accessible to users with active subscriptions.\nSubscription activation requires a fully verified account.",
	)

	responsePath := filepath.Join(root, "blame-response.json")
	response := `{
  "model": "claude-headless",
  "found": true,
  "results": [
    {
      "spec_id": "f4e5d6c",
      "confidence": "high",
      "relevant_lines": [
        "New users must verify their email address before account activation.",
        "Unverified accounts must be restricted to read-only access."
      ]
    },
    {
      "spec_id": "7890abc",
      "confidence": "medium",
      "relevant_lines": [
        "Paid features must only be accessible to users with active subscriptions.",
        "Subscription activation requires a fully verified account."
      ]
    }
  ]
}`
	if err := os.WriteFile(responsePath, []byte(response), 0o644); err != nil {
		t.Fatalf("failed writing response file: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{
			"blame",
			"--root", root,
			"--response-file", responsePath,
			"users must verify their email before accessing paid features",
		}); err != nil {
			t.Fatalf("blame command failed: %v", err)
		}
	})

	if !strings.Contains(out, "blame: 2 specs found") {
		t.Fatalf("expected two results summary, got:\n%s", out)
	}
	first := strings.Index(out, "spec: f4e5d6c")
	second := strings.Index(out, "spec: 7890abc")
	if first == -1 || second == -1 || first > second {
		t.Fatalf("expected result ordering from AI response, got:\n%s", out)
	}
}

func TestBlameCommandNoMatchReportsSpecGap(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}
	ingestSpecForBlame(t, root, "spec-401", "Session Policy", "auth", "2026-02-10T12:00:00Z", []string{"auth"},
		"Sessions must expire after 15 minutes of inactivity.",
	)

	responsePath := filepath.Join(root, "blame-response.json")
	response := `{
  "model": "codex-headless",
  "found": false,
  "results": []
}`
	if err := os.WriteFile(responsePath, []byte(response), 0o644); err != nil {
		t.Fatalf("failed writing response file: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{
			"blame",
			"--root", root,
			"--response-file", responsePath,
			"error messages are displayed in the user's preferred language",
		}); err != nil {
			t.Fatalf("blame command failed: %v", err)
		}
	})

	if !strings.Contains(out, "blame: no matching specs found") {
		t.Fatalf("expected no match summary, got:\n%s", out)
	}
	if !strings.Contains(out, "specification gap") {
		t.Fatalf("expected gap explanation, got:\n%s", out)
	}
	if !strings.Contains(out, `canon raw --text "error messages are displayed in the user's preferred language"`) {
		t.Fatalf("expected spec authoring suggestion, got:\n%s", out)
	}
}

func TestBlameCommandDomainFilterRestrictsResults(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	ingestSpecForBlame(t, root, "spec-auth", "Registration Rules", "auth", "2026-02-10T12:00:00Z", []string{"auth"},
		"Users must verify email before account activation.",
	)
	ingestSpecForBlame(t, root, "spec-billing", "Billing Rules", "billing", "2026-02-10T12:05:00Z", []string{"billing"},
		"Paid features must require an active subscription.",
	)

	responsePath := filepath.Join(root, "blame-response.json")
	response := `{
  "model": "codex-headless",
  "found": true,
  "results": [
    {
      "spec_id": "spec-auth",
      "confidence": "high",
      "relevant_lines": ["Users must verify email before account activation."]
    },
    {
      "spec_id": "spec-billing",
      "confidence": "medium",
      "relevant_lines": ["Paid features must require an active subscription."]
    }
  ]
}`
	if err := os.WriteFile(responsePath, []byte(response), 0o644); err != nil {
		t.Fatalf("failed writing response file: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{
			"blame",
			"--root", root,
			"--domain", "auth",
			"--response-file", responsePath,
			"users must verify email before paid access",
		}); err != nil {
			t.Fatalf("blame command failed: %v", err)
		}
	})

	if !strings.Contains(out, "blame: 1 spec found") {
		t.Fatalf("expected one filtered result, got:\n%s", out)
	}
	if !strings.Contains(out, "spec: spec-auth") {
		t.Fatalf("expected auth spec in output, got:\n%s", out)
	}
	if strings.Contains(out, "spec: spec-billing") {
		t.Fatalf("did not expect billing spec with auth filter, got:\n%s", out)
	}
}

func TestBlameCommandJSONOutput(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	ingestSpecForBlame(t, root, "a1b2c3d", "API Endpoint Design and Versioning", "api", "2026-01-15T10:30:00Z", []string{"api"},
		"All list endpoints must return paginated responses.\nDefault page size must be 25 items.",
	)

	responsePath := filepath.Join(root, "blame-response.json")
	response := `{
  "model": "codex-headless",
  "found": true,
  "results": [
    {
      "spec_id": "a1b2c3d",
      "confidence": "high",
      "relevant_lines": [
        "All list endpoints must return paginated responses.",
        "Default page size must be 25 items."
      ]
    }
  ]
}`
	if err := os.WriteFile(responsePath, []byte(response), 0o644); err != nil {
		t.Fatalf("failed writing response file: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{
			"blame",
			"--root", root,
			"--json",
			"--response-file", responsePath,
			"API responses are paginated with a default page size of 25",
		}); err != nil {
			t.Fatalf("blame command failed: %v", err)
		}
	})

	var payload struct {
		Query   string `json:"query"`
		Found   bool   `json:"found"`
		Results []struct {
			SpecID       string   `json:"spec_id"`
			Title        string   `json:"title"`
			Domain       string   `json:"domain"`
			Confidence   string   `json:"confidence"`
			Created      string   `json:"created"`
			RelevantLine []string `json:"relevant_lines"`
		} `json:"results"`
	}
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("json output is invalid: %v\noutput:\n%s", err, out)
	}
	if payload.Query == "" || !payload.Found {
		t.Fatalf("expected found JSON payload, got: %+v", payload)
	}
	if len(payload.Results) != 1 || payload.Results[0].SpecID != "a1b2c3d" {
		t.Fatalf("unexpected JSON results: %+v", payload.Results)
	}
}

func TestBlameCommandFailsWhenAIProviderUnavailable(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}
	ingestSpecForBlame(t, root, "spec-500", "API Rules", "api", "2026-02-10T12:00:00Z", []string{"api"},
		"API requests must include a tenant header.",
	)

	t.Setenv("PATH", t.TempDir())
	t.Setenv("HOME", t.TempDir())

	err := run([]string{
		"blame",
		"--root", root,
		"API requests include tenant header",
	})
	if err == nil {
		t.Fatalf("expected blame to fail when AI provider is unavailable")
	}
	if !strings.Contains(err.Error(), "runtime-ready") {
		t.Fatalf("expected runtime readiness error, got: %v", err)
	}
}

func ingestSpecForBlame(t *testing.T, root string, id string, title string, domain string, created string, touched []string, body string) {
	t.Helper()
	text := fmt.Sprintf(`---
id: %s
type: feature
title: %q
domain: %s
created: %s
depends_on: []
touched_domains: [%s]
---
%s`, id, title, domain, created, strings.Join(touched, ", "), body)
	if _, err := canon.Ingest(root, canon.IngestInput{Text: text}); err != nil {
		t.Fatalf("Ingest failed for %s: %v", id, err)
	}
}

func TestCheckCommandPassesWithoutConflicts(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	writeCLICheckSpec(t, root, "safe-a", "API Auth", "api", "API endpoints must require authentication.")
	writeCLICheckSpec(t, root, "safe-b", "Billing Retry", "billing", "Billing retries must happen daily.")
	responsePath := writeCLICheckResponse(t, root, map[string]any{
		"model": "codex-headless",
		"conflict_check": map[string]any{
			"has_conflicts": false,
			"summary":       "No conflicts.",
			"conflicts":     []map[string]any{},
		},
	})

	out := captureStdout(t, func() {
		if err := run([]string{"check", "--root", root, "--response-file", responsePath}); err != nil {
			t.Fatalf("check command failed: %v", err)
		}
	})

	if !strings.Contains(out, "check passed: 0 conflicts across 2 specs") {
		t.Fatalf("unexpected check output:\n%s", out)
	}
}

func TestCheckCommandJSONAndExitCodeOnConflicts(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	writeCLICheckSpec(t, root, "conf-a", "Auth Required", "api", "API endpoints must require authentication.")
	writeCLICheckSpec(t, root, "conf-b", "Auth Optional", "api", "API endpoints must not require authentication.")
	responsePath := writeCLICheckResponse(t, root, map[string]any{
		"model": "codex-headless",
		"conflict_check": map[string]any{
			"has_conflicts": true,
			"summary":       "Found conflict.",
			"conflicts": []map[string]any{
				{
					"spec_a":        "conf-a",
					"spec_b":        "conf-b",
					"domain":        "api",
					"statement_key": "api auth required",
					"line_a":        "API endpoints must require authentication.",
					"line_b":        "API endpoints must not require authentication.",
					"reason":        "Direct contradiction.",
				},
			},
		},
	})

	var commandErr error
	out := captureStdout(t, func() {
		commandErr = run([]string{"check", "--root", root, "--json", "--response-file", responsePath})
	})
	if commandErr == nil {
		t.Fatalf("expected non zero behavior when conflicts are detected")
	}

	var payload struct {
		Passed         bool `json:"passed"`
		TotalSpecs     int  `json:"total_specs"`
		TotalConflicts int  `json:"total_conflicts"`
	}
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("failed to parse JSON output: %v\n%s", err, out)
	}
	if payload.Passed {
		t.Fatalf("expected failed check payload")
	}
	if payload.TotalSpecs != 2 || payload.TotalConflicts != 1 {
		t.Fatalf("unexpected check payload: %+v", payload)
	}
}

func TestCheckCommandWriteCreatesConflictReport(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	writeCLICheckSpec(t, root, "write-a", "Audit Required", "auth", "Audit logs must retain user access history.")
	writeCLICheckSpec(t, root, "write-b", "Audit Forbidden", "auth", "Audit logs must not retain user access history.")
	responsePath := writeCLICheckResponse(t, root, map[string]any{
		"model": "codex-headless",
		"conflict_check": map[string]any{
			"has_conflicts": true,
			"summary":       "Found conflict.",
			"conflicts": []map[string]any{
				{
					"spec_a":        "write-a",
					"spec_b":        "write-b",
					"domain":        "auth",
					"statement_key": "audit retention",
					"line_a":        "Audit logs must retain user access history.",
					"line_b":        "Audit logs must not retain user access history.",
					"reason":        "Direct contradiction.",
				},
			},
		},
	})

	var commandErr error
	_ = captureStdout(t, func() {
		commandErr = run([]string{"check", "--root", root, "--write", "--response-file", responsePath})
	})
	if commandErr == nil {
		t.Fatalf("expected conflict check command to return error")
	}

	reports, err := filepath.Glob(filepath.Join(root, ".canon", "conflict-reports", "*.yaml"))
	if err != nil {
		t.Fatalf("failed to list conflict reports: %v", err)
	}
	if len(reports) != 1 {
		t.Fatalf("expected one written conflict report, got %d", len(reports))
	}
}

func TestDepsRiskCommandJSONOutputShape(t *testing.T) {
	root := t.TempDir()
	writeCLIGoMod(t, root, `module example.com/cli-pass

go 1.22

require github.com/acme/stable v1.2.3
`)
	if err := os.WriteFile(filepath.Join(root, "go.sum"), []byte(""), 0o644); err != nil {
		t.Fatalf("failed writing go.sum: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{"deps-risk", "--root", root, "--json"}); err != nil {
			t.Fatalf("deps-risk command failed: %v", err)
		}
	})

	var payload struct {
		DependencyCount int `json:"dependency_count"`
		Summary         struct {
			TotalFindings   int    `json:"total_findings"`
			HighestSeverity string `json:"highest_severity"`
		} `json:"summary"`
	}
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("json output is invalid: %v\noutput:\n%s", err, out)
	}
	if payload.DependencyCount != 1 {
		t.Fatalf("expected dependency count 1, got %d", payload.DependencyCount)
	}
	if payload.Summary.TotalFindings != 0 || payload.Summary.HighestSeverity != "none" {
		t.Fatalf("unexpected summary payload: %+v", payload.Summary)
	}
}

func TestDepsRiskCommandReturnsErrorWhenThresholdExceeded(t *testing.T) {
	root := t.TempDir()
	writeCLIGoMod(t, root, `module example.com/cli-threshold

go 1.22

require github.com/acme/risky v0.9.0
`)

	var commandErr error
	out := captureStdout(t, func() {
		commandErr = run([]string{"deps-risk", "--root", root, "--fail-on", "medium"})
	})
	if commandErr == nil {
		t.Fatalf("expected deps-risk to fail when threshold is exceeded")
	}
	if !strings.Contains(commandErr.Error(), "dependency risk threshold failed") {
		t.Fatalf("unexpected error: %v", commandErr)
	}
	if !strings.Contains(out, "highest severity: high") {
		t.Fatalf("expected output to include high severity summary, got:\n%s", out)
	}
}

func TestDepsRiskCommandRejectsInvalidFailOnSeverity(t *testing.T) {
	err := run([]string{"deps-risk", "--fail-on", "urgent"})
	if err == nil {
		t.Fatalf("expected error for invalid --fail-on severity")
	}
	if !strings.Contains(err.Error(), "invalid --fail-on severity") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestDepsRiskCommandRejectsPositionalArgs(t *testing.T) {
	err := run([]string{"deps-risk", "extra"})
	if err == nil {
		t.Fatalf("expected error for deps-risk positional arguments")
	}
	if !strings.Contains(err.Error(), "does not accept positional arguments") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLoggingAuditCommandJSONOutputShape(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ConflictMode: "off",
		Text: `---
id: loga001
type: feature
title: "Logging Audit Healthy Fixture"
domain: canon
created: 2026-03-06T00:00:00Z
depends_on: []
touched_domains: [canon]
---
Healthy fixture content.
`,
	}); err != nil {
		t.Fatalf("Ingest failed: %v", err)
	}

	out := captureStdout(t, func() {
		if err := run([]string{"logging-audit", "--root", root, "--json"}); err != nil {
			t.Fatalf("logging-audit command failed: %v", err)
		}
	})

	var payload struct {
		LedgerEntries int `json:"ledger_entries"`
		SpecFiles     int `json:"spec_files"`
		SourceFiles   int `json:"source_files"`
		Summary       struct {
			TotalFindings   int    `json:"total_findings"`
			HighestSeverity string `json:"highest_severity"`
		} `json:"summary"`
	}
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("json output is invalid: %v\noutput:\n%s", err, out)
	}
	if payload.LedgerEntries != 1 || payload.SpecFiles != 1 || payload.SourceFiles != 1 {
		t.Fatalf("unexpected artifact counts in payload: %+v", payload)
	}
	if payload.Summary.TotalFindings != 0 || payload.Summary.HighestSeverity != "none" {
		t.Fatalf("unexpected summary payload: %+v", payload.Summary)
	}
}

func TestLoggingAuditCommandReturnsErrorWhenThresholdExceeded(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}
	if _, err := canon.Ingest(root, canon.IngestInput{
		ConflictMode: "off",
		Text: `---
id: loga002
type: feature
title: "Logging Audit Threshold Fixture"
domain: canon
created: 2026-03-06T00:10:00Z
depends_on: []
touched_domains: [canon]
---
Fixture content for threshold test.
`,
	}); err != nil {
		t.Fatalf("Ingest failed: %v", err)
	}

	ledgerPaths, err := filepath.Glob(filepath.Join(root, ".canon", "ledger", "*.json"))
	if err != nil {
		t.Fatalf("failed listing ledger entries: %v", err)
	}
	if len(ledgerPaths) != 1 {
		t.Fatalf("expected one ledger entry, got %d", len(ledgerPaths))
	}

	var entry canon.LedgerEntry
	b, err := os.ReadFile(ledgerPaths[0])
	if err != nil {
		t.Fatalf("failed reading ledger fixture: %v", err)
	}
	if err := json.Unmarshal(b, &entry); err != nil {
		t.Fatalf("failed decoding ledger fixture: %v", err)
	}
	entry.ContentHash = "deadbeef"
	updated, err := json.MarshalIndent(entry, "", "  ")
	if err != nil {
		t.Fatalf("failed encoding tampered ledger fixture: %v", err)
	}
	updated = append(updated, '\n')
	if err := os.WriteFile(ledgerPaths[0], updated, 0o644); err != nil {
		t.Fatalf("failed writing tampered ledger fixture: %v", err)
	}

	var commandErr error
	out := captureStdout(t, func() {
		commandErr = run([]string{"logging-audit", "--root", root, "--fail-on", "medium"})
	})
	if commandErr == nil {
		t.Fatalf("expected logging-audit to fail when threshold is exceeded")
	}
	if !strings.Contains(commandErr.Error(), "logging-audit threshold failed") {
		t.Fatalf("unexpected error: %v", commandErr)
	}
	if !strings.Contains(out, "highest severity: high") {
		t.Fatalf("expected output to include high severity summary, got:\n%s", out)
	}
}

func TestLoggingAuditCommandRejectsInvalidFailOnSeverity(t *testing.T) {
	err := run([]string{"logging-audit", "--fail-on", "urgent"})
	if err == nil {
		t.Fatalf("expected error for invalid --fail-on severity")
	}
	if !strings.Contains(err.Error(), "invalid --fail-on severity") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLoggingAuditCommandRejectsPositionalArgs(t *testing.T) {
	err := run([]string{"logging-audit", "extra"})
	if err == nil {
		t.Fatalf("expected error for logging-audit positional arguments")
	}
	if !strings.Contains(err.Error(), "does not accept positional arguments") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandJSONOutputWithResponseFile(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "src"), 0o755); err != nil {
		t.Fatalf("failed creating src directory: %v", err)
	}
	policyPath := filepath.Join(root, "privacy-policy.md")
	if err := os.WriteFile(policyPath, []byte("# Privacy Policy\n\nWe encrypt personal data at rest.\n"), 0o644); err != nil {
		t.Fatalf("failed writing policy fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "src", "crypto.go"), []byte("package src\n\nfunc Encrypt() {}\n"), 0o644); err != nil {
		t.Fatalf("failed writing code fixture: %v", err)
	}

	responsePath := filepath.Join(root, "privacy-response.json")
	writeGCResponse(t, responsePath, map[string]any{
		"model": "fixture-model",
		"findings": []map[string]any{
			{
				"claim_id":          "claim-enc-at-rest",
				"claim":             "We encrypt personal data at rest.",
				"status":            "supported",
				"severity":          "low",
				"reason":            "Encryption helper exists in source.",
				"evidence_paths":    []string{"src/crypto.go"},
				"evidence_snippets": []string{"func Encrypt() {}"},
			},
		},
	})

	out := captureStdout(t, func() {
		if err := run([]string{
			"privacy-check",
			"--root", root,
			"--policy-file", policyPath,
			"--code-path", "src",
			"--response-file", responsePath,
			"--json",
		}); err != nil {
			t.Fatalf("privacy-check command failed: %v", err)
		}
	})

	var payload struct {
		PolicyFile string `json:"policy_file"`
		Summary    struct {
			TotalFindings   int    `json:"total_findings"`
			HighestSeverity string `json:"highest_severity"`
		} `json:"summary"`
		Findings []struct {
			ClaimID string `json:"claim_id"`
			Status  string `json:"status"`
		} `json:"findings"`
	}
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("privacy-check JSON output is invalid: %v\noutput:\n%s", err, out)
	}
	if filepath.ToSlash(payload.PolicyFile) != filepath.ToSlash(policyPath) {
		t.Fatalf("unexpected policy file in output: %s", payload.PolicyFile)
	}
	if payload.Summary.TotalFindings != 1 || payload.Summary.HighestSeverity != "low" {
		t.Fatalf("unexpected summary payload: %+v", payload.Summary)
	}
	if len(payload.Findings) != 1 || payload.Findings[0].ClaimID != "claim-enc-at-rest" || payload.Findings[0].Status != "supported" {
		t.Fatalf("unexpected findings payload: %+v", payload.Findings)
	}
}

func TestPrivacyCheckCommandRequiresPolicyFile(t *testing.T) {
	err := run([]string{"privacy-check", "--response-file", "resp.json"})
	if err == nil {
		t.Fatalf("expected missing policy-file error")
	}
	if !strings.Contains(err.Error(), "privacy-check requires --policy-file") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandRejectsInvalidFailOnSeverity(t *testing.T) {
	root := t.TempDir()
	policyPath := filepath.Join(root, "policy.md")
	if err := os.WriteFile(policyPath, []byte("policy"), 0o644); err != nil {
		t.Fatalf("failed writing policy fixture: %v", err)
	}

	err := run([]string{"privacy-check", "--root", root, "--policy-file", policyPath, "--fail-on", "urgent"})
	if err == nil {
		t.Fatalf("expected invalid fail-on severity error")
	}
	if !strings.Contains(err.Error(), "invalid --fail-on severity") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandRejectsPositionalArgs(t *testing.T) {
	err := run([]string{"privacy-check", "extra"})
	if err == nil {
		t.Fatalf("expected positional argument validation error")
	}
	if !strings.Contains(err.Error(), "does not accept positional arguments") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandRequiresResponseFileForFromResponseMode(t *testing.T) {
	root := t.TempDir()
	policyPath := filepath.Join(root, "policy.md")
	if err := os.WriteFile(policyPath, []byte("policy"), 0o644); err != nil {
		t.Fatalf("failed writing policy fixture: %v", err)
	}

	err := run([]string{"privacy-check", "--root", root, "--policy-file", policyPath, "--ai", "from-response"})
	if err == nil {
		t.Fatalf("expected from-response response-file validation error")
	}
	if !strings.Contains(err.Error(), "requires --response-file") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandRejectsUnsupportedAIMode(t *testing.T) {
	root := t.TempDir()
	policyPath := filepath.Join(root, "policy.md")
	if err := os.WriteFile(policyPath, []byte("policy"), 0o644); err != nil {
		t.Fatalf("failed writing policy fixture: %v", err)
	}

	err := run([]string{"privacy-check", "--root", root, "--policy-file", policyPath, "--ai", "off"})
	if err == nil {
		t.Fatalf("expected unsupported ai mode error")
	}
	if !strings.Contains(err.Error(), "unsupported privacy-check ai mode") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPrivacyCheckCommandThresholdFailureReturnsError(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "src"), 0o755); err != nil {
		t.Fatalf("failed creating src directory: %v", err)
	}
	policyPath := filepath.Join(root, "privacy-policy.md")
	if err := os.WriteFile(policyPath, []byte("# Privacy Policy\n\nUsers can always delete account data.\n"), 0o644); err != nil {
		t.Fatalf("failed writing policy fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "src", "retention.go"), []byte("package src\n\nfunc RetainForever() {}\n"), 0o644); err != nil {
		t.Fatalf("failed writing code fixture: %v", err)
	}

	responsePath := filepath.Join(root, "privacy-response-threshold.json")
	writeGCResponse(t, responsePath, map[string]any{
		"model": "fixture-model",
		"findings": []map[string]any{
			{
				"claim_id":          "claim-delete",
				"claim":             "Users can always delete account data.",
				"status":            "contradicted",
				"severity":          "high",
				"reason":            "Retention function keeps records indefinitely.",
				"evidence_paths":    []string{"src/retention.go"},
				"evidence_snippets": []string{"func RetainForever() {}"},
			},
		},
	})

	var commandErr error
	out := captureStdout(t, func() {
		commandErr = run([]string{
			"privacy-check",
			"--root", root,
			"--policy-file", policyPath,
			"--code-path", "src",
			"--response-file", responsePath,
			"--fail-on", "medium",
		})
	})
	if commandErr == nil {
		t.Fatalf("expected privacy-check threshold failure")
	}
	if !strings.Contains(commandErr.Error(), "privacy-check threshold failed") {
		t.Fatalf("unexpected threshold error: %v", commandErr)
	}
	if !strings.Contains(out, "highest severity: high") {
		t.Fatalf("expected text output with highest severity, got:\n%s", out)
	}
}

func writeCLICheckSpec(t *testing.T, root string, id string, title string, domain string, body string) {
	t.Helper()
	text := `---
id: ` + id + `
type: feature
title: "` + title + `"
domain: ` + domain + `
created: 2026-02-21T00:00:00Z
depends_on: []
touched_domains: [` + domain + `]
---
` + body + `
`
	path := filepath.Join(root, ".canon", "specs", id+".spec.md")
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		t.Fatalf("failed writing check spec %s: %v", id, err)
	}
}

func writeCLICheckResponse(t *testing.T, root string, payload map[string]any) string {
	t.Helper()
	b, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		t.Fatalf("failed marshaling check response: %v", err)
	}
	path := filepath.Join(root, "ai-check-response.json")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		t.Fatalf("failed writing check response: %v", err)
	}
	return path
}

func writeGCResponse(t *testing.T, path string, payload map[string]any) {
	t.Helper()
	b, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		t.Fatalf("failed to marshal gc response: %v", err)
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		t.Fatalf("failed writing gc response: %v", err)
	}
}

func writeCLIGoMod(t *testing.T, root string, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(content), 0o644); err != nil {
		t.Fatalf("failed writing go.mod fixture: %v", err)
	}
}
