package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"canon/internal/canon"
)

func TestRenderDefaultsToAIRenderAndWritesStateFolder(t *testing.T) {
	root := t.TempDir()
	if err := canon.EnsureLayout(root, true); err != nil {
		t.Fatalf("EnsureLayout failed: %v", err)
	}

	if _, err := canon.Ingest(root, canon.IngestInput{
		Text:   "Billing retries must happen daily.",
		Title:  "Billing Retry",
		Domain: "billing",
	}); err != nil {
		t.Fatalf("Ingest failed: %v", err)
	}

	binDir := t.TempDir()
	codexPath := filepath.Join(binDir, "codex")
	script := `#!/bin/sh
out=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    out="$2"
    shift 2
    continue
  fi
  shift
done

if [ -z "$out" ]; then
  echo "missing output path" >&2
  exit 2
fi

cat >/dev/null

cat <<'JSON' > "$out"
{
  "model": "codex-headless",
  "domain_docs": [
    {
      "domain": "billing",
      "body": "<!-- AUTO-GENERATED by canon. Do not edit directly. -->\n<!-- Domain: billing -->\n<!-- Contributing specs: spec-000 -->\n\n# BILLING\n\n## Effective State\n\n- AI-effective state for billing.\n"
    }
  ],
  "interaction_docs": [],
  "gaps": "<!-- AUTO-GENERATED by canon. Do not edit directly. -->\n# Known Gaps\n\nNo unresolved gaps.\n"
}
JSON
`
	if err := os.WriteFile(codexPath, []byte(script), 0o755); err != nil {
		t.Fatalf("failed writing fake codex binary: %v", err)
	}

	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("HOME", t.TempDir())

	if err := run([]string{"render", "--root", root, "--write"}); err != nil {
		t.Fatalf("render command failed: %v", err)
	}

	billingState, err := os.ReadFile(filepath.Join(root, "state", "billing.md"))
	if err != nil {
		t.Fatalf("failed reading billing state file: %v", err)
	}
	if !strings.Contains(string(billingState), "AI-effective state for billing.") {
		t.Fatalf("expected AI render content in state/billing.md")
	}

	if _, err := os.Stat(filepath.Join(root, "state2")); err == nil {
		t.Fatalf("did not expect render output in state2/")
	} else if !os.IsNotExist(err) {
		t.Fatalf("failed checking state2 folder: %v", err)
	}
}
